# Generated by Django 3.2.12 on 2022-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=20)),
                ('file_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
