# Generated by Django 3.2.12 on 2022-05-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0002_file_file_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='file_id',
        ),
    ]
