# Generated by Django 3.2.12 on 2022-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0003_auto_20220525_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(default='', max_length=200),
        ),
    ]
