# Generated by Django 3.2.12 on 2022-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0004_user_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
