# Generated by Django 3.2.12 on 2022-05-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0006_rename_author_id_file_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='authorId',
            new_name='author_id',
        ),
    ]
