# Generated by Django 3.2.12 on 2022-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0008_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_lenth',
            field=models.IntegerField(default=0),
        ),
    ]
